/*
* AUTOGENERATED FILE
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))=
        "****************"  // placeholder for beggining
        "20260217T191901"   // DateTime using ISO-8601 format
        " "                 // alignment
        "019403b6"          // STLIB commit
        "--------"          // ADJ commit
        "21ba3add"          // Board commit
        // the '=' is used for unparsing
        ;
}