/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20251208T123919"   // DateTime using ISO-8601 format
        " "                 // alignment
        "d9263fee"          // STLIB commit
        "--------"          // ADJ commit
        "a6e33160"          // Board commit
        // the '=' is used for unparsing
        ;
}