/*
 * AUTOGENERATED FILE
 * DO NOT MODIFY MANUALLY!!!
 */
extern "C" {
const char DESCRIPTION[255] __attribute__((section(".metadata_pool"))) =
    "****************" // placeholder for beggining
    "20260316T224044"  // DateTime using ISO-8601 format
    " "                // alignment
    "aaecc655"         // STLIB commit
    "--------"         // ADJ commit
    "9d2ba8c9"         // Board commit
    // the '=' is used for unparsing
    ;
}
