#pragma once
#include "ST-LIB.hpp"

/*Data packets for {{board}} 
-AUTOGENERATED CODE, DO NOT MODIFY-*/
class DataPackets{
public:
    {% for enum in enums -%}
    enum class {{enum.name}} : uint8_t 
    {
    {%- for value in enum["values"] %}
        {{value}} = {{loop.index0}},
    {%- endfor %}
    };
    {% endfor %}
    
    {% for packet in packets -%}
    static void {{packet.name}}_init({% for variable in packet.variables %}{{variable.type}} &{{variable.name}}{% if not loop.last %}, {% endif %}{% endfor %})
    {
        {{packet.name}}_packet = new HeapPacket(static_cast<uint16_t>({{packet.id}}){% if packet.variables %}, {% for variable in packet.variables %}&{{variable.name}}{% if not loop.last %}, {% endif %}{% endfor %}{% endif %});
    }
    
    {% endfor -%}
    
public:
    {%for packet in packets -%}
    inline static HeapPacket *{{packet.name}}_packet{nullptr};
    {% endfor %}
    {% for socket in sockets -%}
    inline static {{socket.type}} *{{socket.name}}{nullptr};
    {% endfor %}
        
    static void start()
    {   
        {% for packet in packets -%}
        if ({{packet.name}}_packet == nullptr) {
            ErrorHandler("Packet {{packet.name}} not initialized");
        }
        {% endfor %}

        {% for socket in ServerSockets -%}
        {{socket.name}} = new ServerSocket("{{socket.board_ip}}",{{socket.port}});
        {%- endfor %}
        {% for socket in DatagramSockets -%}
        {{socket.name}} = new DatagramSocket("{{socket.board_ip}}",{{socket.port}},"{{socket.remote_ip}}",{{socket.port}});
        {% endfor %}
        {% for socket in Sockets -%}
        {{socket.name}} = new Socket("{{socket.board_ip}}",{{socket.local_port}},"{{socket.remote_ip}}",{{socket.remote_port}});
        {% endfor %}
        
        {%- for packet in sending_packets %}
        Scheduler::register_task({% if packet.period_type == "ms" %}{{ (packet.period*1000)|round|int }}{% else %}{{ packet.period|round|int }}{% endif %}, +[](){
            {% if packet.name is string -%}
            DataPackets::{{packet.socket}}->send_packet(*DataPackets::{{packet.name}}_packet);
            {% else %}
            {% for name in packet.name -%}
            DataPackets::{{packet.socket}}->send_packet(*DataPackets::{{name}}_packet);
            {% endfor -%}
            {%- endif %}
        }); {%- endfor %}
    }


   
};
