#pragma once
#include "ST-LIB.hpp"

/*Data packets for {{board}}
-AUTOGENERATED CODE, DO NOT MODIFY-*/

#ifndef ARRAY_LEN
#define ARRAY_LEN(Arr) (sizeof(Arr)/sizeof(Arr[0]))
#endif
class DataPackets{
public:
    {% for enum in enums -%}
    enum class {{enum.name}} : uint8_t
    {
    {%- for value in enum["values"] %}
        {{value}} = {{loop.index0}},
    {%- endfor %}
    };
    {% endfor %}
#ifdef STLIB_ETH
    {% for packet in packets -%}
    static void {{packet.name}}_init({% for variable in packet.variables %}{{variable.type}} &{{variable.name}}{% if not loop.last %}, {% endif %}{% endfor %})
    {
        {{packet.name}}_packet = new StackPacket(static_cast<uint16_t>({{packet.id}}){% if packet.variables %}, {% for variable in packet.variables %}&{{variable.name}}{% if not loop.last %}, {% endif %}{% endfor %}{% endif %});
    }

    {% endfor -%}
#endif

public:
#ifdef STLIB_ETH
    {%for packet in packets -%}
    inline static Packet *{{packet.name}}_packet{nullptr};
    {% endfor %}

    {% for group in sending_packets -%}
    inline static uint32_t group_{{loop.index0}}_idx = 0;
    inline static Packet **group_{{loop.index0}}[] = { {% for packet in group.packets %}&{{packet.name}}_packet{% if not loop.last %}, {% endif %}{% endfor %} };
    {% endfor %}

    {% for socket in DatagramSockets -%}
    inline static {{socket.type}} *{{socket.name}}{nullptr};
    {% endfor %}
#endif

    static void start()
    {
#ifdef STLIB_ETH
        {% for packet in packets -%}
        if ({{packet.name}}_packet == nullptr) {
            PANIC("Packet {{packet.name}} not initialized");
        }
        {% endfor %}

        {% for socket in DatagramSockets -%}
        {{socket.name}} = new DatagramSocket("{{socket.board_ip}}",{{socket.port}},"{{socket.remote_ip}}",{{socket.port}});
        {% endfor %}

        {%- for group in sending_packets %}
        Scheduler::register_task({% if group.period_type == "ms" %}{{ (group.period*1000)|round|int }}{% else %}{{ group.period|round|int }}{% endif %} / ARRAY_LEN(DataPackets::group_{{loop.index0}}), +[](){
            Packet *packet = *DataPackets::group_{{loop.index0}}[DataPackets::group_{{loop.index0}}_idx];
            DataPackets::{{group.packets[0].socket}}->send_packet(*packet);
            DataPackets::group_{{loop.index0}}_idx = (DataPackets::group_{{loop.index0}}_idx + 1) % ARRAY_LEN(DataPackets::group_{{loop.index0}});
        });
        {%- endfor %}
#endif
    }



};
