#pragma once
#include "ST-LIB.hpp"

/*Order packets for {{board}}
-AUTOGENERATED CODE, DO NOT MODIFY- */


class OrderPackets{
public:
    {% for enum in enums -%}
    enum class {{enum.name}} : uint8_t
    {
    {%- for value in enum["values"] %}
        {{value}} = {{loop.index0}},
    {%- endfor %}
    };
    {% endfor %}

    {% for packet in packets -%}
    inline static bool {{packet.name}}_flag{false};
    {% endfor %}

    OrderPackets() = default;

    {% for packet in packets -%}
    inline static HeapOrder *{{packet.name}}_order{nullptr};
    {% endfor %}

    {% for packet in packets -%}
    static void {{packet.name}}_init({% for variable in packet.variables %}{{variable.type}} &{{variable.name}}{% if not loop.last %}, {% endif %}{% endfor %})
    {
        {{packet.name}}_order = new HeapOrder({{packet.id}}, &{{packet.name}}_cb{% if packet.variables %}, {% for variable in packet.variables %}&{{variable.name}}{% if not loop.last %}, {% endif %}{% endfor %}{% endif %});
    }
    {% endfor %}

    {% for socket in Sockets -%}
    inline static {{socket.type}} *{{socket.name}}{nullptr};
    {% endfor %}
    {% for socket in ServerSockets -%}
    inline static {{socket.type}} *{{socket.name}}{nullptr};
    {% endfor %}

    static void start()
    {
        {% for packet in packets -%}
        if ({{packet.name}}_order == nullptr) {
            ErrorHandler("Order {{packet.name}} not initialized");
        }
        {% endfor %}

        {% for socket in ServerSockets -%}
        {{socket.name}} = new ServerSocket("{{socket.board_ip}}",{{socket.port}});
        {%- endfor %}
        {% for socket in Sockets -%}
        {{socket.name}} = new Socket("{{socket.board_ip}}",{{socket.local_port}},"{{socket.remote_ip}}",{{socket.remote_port}});
        {% endfor %}
    }

private:
    {% for packet in packets -%}
    static void {{packet.name}}_cb()
    {
        {{packet.name}}_flag = true;
    }
    {% endfor %}
};
