#pragma once
#include "ST-LIB.hpp"

/*Data packets for TEST
-AUTOGENERATED CODE, DO NOT MODIFY-*/
class DataPackets {
public:
    enum class mirror_mode : uint8_t {
        IDLE = 0,
        RUN = 1,
        SAFE = 2,
        CAL = 3,
    };
    enum class mirror_state : uint8_t {
        BOOT = 0,
        ARMED = 1,
        STREAMING = 2,
        ERROR = 3,
    };
    enum class probe_mode : uint8_t {
        LOW = 0,
        MEDIUM = 1,
        HIGH = 2,
        TURBO = 3,
    };

    static void order_mirror_init(
        uint32_t& tcp_order_count,
        uint16_t& last_order_code,
        bool& enable_flag,
        uint8_t& small_counter,
        int16_t& offset_value,
        mirror_mode& mirror_mode
    ) {
        order_mirror_packet = new HeapPacket(
            static_cast<uint16_t>(20737),
            &tcp_order_count,
            &last_order_code,
            &enable_flag,
            &small_counter,
            &offset_value,
            &mirror_mode
        );
    }

    static void numeric_mirror_init(
        uint16_t& window_size,
        uint32_t& magic_value,
        int32_t& position_value,
        float& ratio_value,
        double& precise_value
    ) {
        numeric_mirror_packet = new HeapPacket(
            static_cast<uint16_t>(20738),
            &window_size,
            &magic_value,
            &position_value,
            &ratio_value,
            &precise_value
        );
    }

    static void extremes_mirror_init(
        int8_t& trim_value,
        int64_t& energy_value,
        uint64_t& big_counter,
        mirror_state& mirror_state
    ) {
        extremes_mirror_packet = new HeapPacket(
            static_cast<uint16_t>(20739),
            &trim_value,
            &energy_value,
            &big_counter,
            &mirror_state
        );
    }

    static void udp_probe_init(
        uint32_t& probe_seq,
        bool& probe_toggle,
        uint16_t& probe_window,
        float& probe_ratio,
        probe_mode& probe_mode
    ) {
        udp_probe_packet = new HeapPacket(
            static_cast<uint16_t>(20740),
            &probe_seq,
            &probe_toggle,
            &probe_window,
            &probe_ratio,
            &probe_mode
        );
    }

    static void udp_probe_echo_init(
        uint32_t& udp_parse_count,
        uint32_t& probe_seq,
        bool& probe_toggle,
        uint16_t& probe_window,
        float& probe_ratio,
        probe_mode& probe_mode
    ) {
        udp_probe_echo_packet = new HeapPacket(
            static_cast<uint16_t>(20741),
            &udp_parse_count,
            &probe_seq,
            &probe_toggle,
            &probe_window,
            &probe_ratio,
            &probe_mode
        );
    }

    static void heartbeat_snapshot_init(
        uint32_t& heartbeat_ticks,
        uint32_t& tcp_order_count,
        uint32_t& udp_parse_count,
        mirror_state& mirror_state
    ) {
        heartbeat_snapshot_packet = new HeapPacket(
            static_cast<uint16_t>(20742),
            &heartbeat_ticks,
            &tcp_order_count,
            &udp_parse_count,
            &mirror_state
        );
    }

public:
    inline static HeapPacket* order_mirror_packet{nullptr};
    inline static HeapPacket* numeric_mirror_packet{nullptr};
    inline static HeapPacket* extremes_mirror_packet{nullptr};
    inline static HeapPacket* udp_probe_packet{nullptr};
    inline static HeapPacket* udp_probe_echo_packet{nullptr};
    inline static HeapPacket* heartbeat_snapshot_packet{nullptr};

    inline static DatagramSocket* telemetry_udp{nullptr};

    static void start() {
        if (order_mirror_packet == nullptr) {
            ErrorHandler("Packet order_mirror not initialized");
        }
        if (numeric_mirror_packet == nullptr) {
            ErrorHandler("Packet numeric_mirror not initialized");
        }
        if (extremes_mirror_packet == nullptr) {
            ErrorHandler("Packet extremes_mirror not initialized");
        }
        if (udp_probe_packet == nullptr) {
            ErrorHandler("Packet udp_probe not initialized");
        }
        if (udp_probe_echo_packet == nullptr) {
            ErrorHandler("Packet udp_probe_echo not initialized");
        }
        if (heartbeat_snapshot_packet == nullptr) {
            ErrorHandler("Packet heartbeat_snapshot not initialized");
        }

        telemetry_udp = new DatagramSocket("192.168.1.7", 41001, "192.168.1.9", 41001);

        Scheduler::register_task(
            50000,
            +[]() {
                DataPackets::telemetry_udp->send_packet(*DataPackets::order_mirror_packet);
                DataPackets::telemetry_udp->send_packet(*DataPackets::numeric_mirror_packet);
                DataPackets::telemetry_udp->send_packet(*DataPackets::extremes_mirror_packet);
                DataPackets::telemetry_udp->send_packet(*DataPackets::udp_probe_echo_packet);
            }
        );
        Scheduler::register_task(
            250000,
            +[]() {
                DataPackets::telemetry_udp->send_packet(*DataPackets::heartbeat_snapshot_packet);
            }
        );
    }
};
