#pragma once
#include "ST-LIB.hpp"

/*Order packets for TEST
-AUTOGENERATED CODE, DO NOT MODIFY- */

class OrderPackets {
public:
    enum class order_mode : uint8_t {
        IDLE = 0,
        RUN = 1,
        SAFE = 2,
        CAL = 3,
    };
    enum class order_state : uint8_t {
        BOOT = 0,
        ARMED = 1,
        STREAMING = 2,
        ERROR = 3,
    };

    inline static bool set_small_profile_flag{false};
    inline static bool set_large_profile_flag{false};
    inline static bool set_extremes_flag{false};
    inline static bool bump_state_flag{false};
    inline static bool set_state_code_flag{false};

    OrderPackets() = default;

    inline static HeapOrder* set_small_profile_order{nullptr};
    inline static HeapOrder* set_large_profile_order{nullptr};
    inline static HeapOrder* set_extremes_order{nullptr};
    inline static HeapOrder* bump_state_order{nullptr};
    inline static HeapOrder* set_state_code_order{nullptr};

    static void set_small_profile_init(
        bool& enable_flag,
        uint8_t& small_counter,
        int16_t& offset_value,
        order_mode& order_mode
    ) {
        set_small_profile_order = new HeapOrder(
            20481,
            &set_small_profile_cb,
            &enable_flag,
            &small_counter,
            &offset_value,
            &order_mode
        );
    }
    static void set_large_profile_init(
        uint16_t& window_size,
        uint32_t& magic_value,
        int32_t& position_value,
        float& ratio_value,
        double& precise_value
    ) {
        set_large_profile_order = new HeapOrder(
            20482,
            &set_large_profile_cb,
            &window_size,
            &magic_value,
            &position_value,
            &ratio_value,
            &precise_value
        );
    }
    static void
    set_extremes_init(int8_t& trim_value, int64_t& energy_value, uint64_t& big_counter) {
        set_extremes_order =
            new HeapOrder(20483, &set_extremes_cb, &trim_value, &energy_value, &big_counter);
    }
    static void bump_state_init() { bump_state_order = new HeapOrder(20484, &bump_state_cb); }
    static void set_state_code_init(order_state& order_state) {
        set_state_code_order = new HeapOrder(20485, &set_state_code_cb, &order_state);
    }

    inline static Socket* control_test_client{nullptr};

    inline static ServerSocket* control_test_tcp{nullptr};

    static void start() {
        if (set_small_profile_order == nullptr) {
            ErrorHandler("Order set_small_profile not initialized");
        }
        if (set_large_profile_order == nullptr) {
            ErrorHandler("Order set_large_profile not initialized");
        }
        if (set_extremes_order == nullptr) {
            ErrorHandler("Order set_extremes not initialized");
        }
        if (bump_state_order == nullptr) {
            ErrorHandler("Order bump_state not initialized");
        }
        if (set_state_code_order == nullptr) {
            ErrorHandler("Order set_state_code not initialized");
        }

        control_test_tcp = new ServerSocket("192.168.1.7", 41000);
        control_test_client = new Socket("192.168.1.7", 41002, "192.168.1.9", 41003);
    }

private:
    static void set_small_profile_cb() { set_small_profile_flag = true; }
    static void set_large_profile_cb() { set_large_profile_flag = true; }
    static void set_extremes_cb() { set_extremes_flag = true; }
    static void bump_state_cb() { bump_state_flag = true; }
    static void set_state_code_cb() { set_state_code_flag = true; }
};
